import view.template.script_down as sct_down

def init():
    return ("<footer class='page-footer black'>"
    "<div class='row'>"
    "<div class=col s2'>"
    "<img id='logo' class='col' src='{{ url_for('static', filename='img/logo.jpeg')}}' style='width: 130px; height: 130px; ' >"
    "</div>"
    "<div class='col s4 offset-s1' >"
    "<a href='#' class='col'><img id='ico-twitter' class='col' src='{{ url_for('static', filename='img/ico-twitter.png')}}' style='width: 50px; height: 30px; position: relative; top: 50px;' ></a>"
    "<a href='#' class='col'><img id='ico-facebook' class='col' src='{{ url_for('static', filename='img/ico-facebook.png')}}' style='width: 60px; height: 40px; position: relative; top: 45px;' ></a>"
    "<a href='#' class='col'><img id='ico-instagram' class='col' src='{{ url_for('static', filename='img/ico-instagram.png')}}' style='width: 50px; height: 30px; position: relative; top: 48px;' ></a>"
    "<a href='#' class='col'><img id='ico-youtube' class='col' src='{{ url_for('static', filename='img/ico-youtube.png')}}' style='width: 60px; height: 40px; position: relative; top: 43px;' ></a>"
    "</div>"
    "<div class='col s3 offset-s3 container'>"
    "<h5 class='white-text'>SOBRE K&K</h5>"
    "<ul>"
    "<li><a class='grey-text text-lighten-3' href='#!'>Nuestro origen y nuestra visión</a></li>"
    "<li><a class='grey-text text-lighten-3' href='#!'>Nuestro compromiso</a></li>"
    "<li><a class='grey-text text-lighten-3' href='#!'>Contáctanos</a></li>"
    #"<li><a class='grey-text text-lighten-3' href='#!'>Link 4</a></li>"
    "</ul>"
    "</div>"
    "</div>"
    "<div class='footer-copyright'>"
    "<div class='container'>"
    "© 2021 Copyright K&K. All Rights Reserved"
    "<a class='grey-text text-lighten-4 right' href='#!'>Atención al cliente</a>"
    "</div>"
    "</div>"
    "</footer>"+ sct_down.Init())