def initHead():
    return("<link rel='stylesheet' href='{{ url_for('static', filename='css/materialize.css') }}' >"
        "<link rel='stylesheet' href='{{ url_for('static', filename='css/materialize.min.css') }}' >"
        "<link href='https://fonts.googleapis.com/icon?family=Material+Icons' rel='stylesheet' >"
        "<style type='text/css'>"
        #-----IMPORTANT Block------
        "@font-face{"
        "font-family: rockwell;"
        "src: url({{ url_for('static', filename='fonts/Rockwell.ttf') }})"
        "}"

        "@font-face{"
        "font-family: robotoSlab;"
        "src: url({{ url_for('static', filename='fonts/RobotoSlab.ttf') }})"
        "}"

        "@font-face{"
        "font-family: notoSansKR;"
        "src: url({{ url_for('static', filename='fonts/NotoSansKR.otf') }})"
        "}"

        "i{"
        "font-size: 1.6vw !important;"
        "}"

        "nav, nav .nav-wrapper i, nav a.button-collapse, nav a.button-collapse i{"
        "line-height: 64px;"
        "}"

        ".input-field label"
        "{"
        "height: 3vw;"
        "}"

        "nav ul a {"
        "font-size: 1.3vw;"
        "}"

        "h4{"
        "font-size: 2.1vw;"
        "}"

        ".row .col{"
        "padding: 0 5.2px;"
        "}"

        "input:not([type]), input[type=text]:not(.browser-default), input[type=password]:not(.browser-default), input[type=email]:not(.browser-default), input[type=url]:not(.browser-default), input[type=time]:not(.browser-default), input[type=date]:not(.browser-default), input[type=datetime]:not(.browser-default), input[type=datetime-local]:not(.browser-default), input[type=tel]:not(.browser-default), input[type=number]:not(.browser-default), input[type=search]:not(.browser-default), textarea.materialize-textarea{"
        "font-size: 12px !important;"
        "}"

        "h6{"
        "margin: 5px 0 0 0;"
        "margin-block-start: 5px;"
        "margin-block-end: 5px;"
        "}"

        "input[type=search]{"
        "border-bottom: 1px solid #9e9e9e !important;"
        "}"

        "body{"
        "background-color: #E9E9E9;"
        "}"
        "header{"
        "font-family: rockwell;"
        "min-height: 64px !important;"
        "margin: 0 !important;"
        "}"
        "#search-field.input-field input[type=search]:focus{"
        "border-radius: 5vw;"
        "}"
        "#container-search{"
        "width: 18.3vw;"
        "}"
        "nav{"
        "background-color: transparent !important;"
        "}"
        "#nameBusiness{"
        "width: 180.4px;"
        "position: relative;"
        "z-index: 1;"
        "left: 32.5px;"
        "}"
        "#nameBusiness > h6{"
        "font-size: 18.6px;"
        "display: inline-block;"
        "vertical-align: middle;"
        "line-height: 150%;"
        "color: #CC0000;"
        "}"
        "#nameBusiness > h6 > span:nth-child(n + 2){"
        "color: #FEFEFE;"
        "}"
        "#nameBusiness > h6 > span:nth-child(1){"
        "color: #333333;"
        "}"
        "#nameBusiness > h6 > span:nth-child(3){"
        "font-size: 8.7px;"
        "white-space: nowrap;"
        "line-height: 12px;"
        "}"
        "#logo{"
        "width: 59px;"
        "height: 49px;"
        "position: absolute;"
        "}"
        "#body-search{"
        "position: relative;"
        "top: 0.63vw;"
        "}"
        "#ico-search{"
        "position: absolute;"
        "left: 5px;"
        "top: -15px;"
        "display: flex;"
        "align-items: center;"
        "}"
        "#ico-search i"
        "{"
        #"background-color: red;"
        "display: contents;"
        "}"
        "#search{"
        "text-indent: 0;"
        "width: 100%;"
        "}"
        "#right_side_header{"
        "white-space: nowrap;"
        "position: absolute;"
        "right: 2vw;"
        "display: flex;"
        "align-items: center;"
        "}"
        "#btn-login{"
        "margin-left: 20px;"
        "font-size: 1.0em;"
        "}"
        "#navbar-container-search{"
        "height: 50px;"
        "}"
        "@media only screen and (max-width: 600px){"
        "body{"
        "font-size:1.0em;"
        "min-width: 600px;"
        "}"
        "#right_side_header{"
        "position: static;"
        "}"
        ":placeholder-shown,::placeholder, ::-webkit-input-placeholder{"
        "font-size: 0.9em;"
        "}"
        "}"
        "@media only screen and (min-width: 601px){"
        "body{"
        "font-size:1.7vw;"
        "}"
        "}"
        "@media only screen and (max-width: 992px){"
        ".ico-person{"
        "top: 3.5px !important;"
        "}"
        ".input-field label"
        "{"
        "height: 4em;"
        "}"
        ".ico-menu{"
        "font-size: 25px !important;"
        "}"
        "i{"
        "font-size: 20px !important;"
        "}"
        "#nameBusiness{"
        "padding-left: 10px;"
        "padding-right: 10px;"
        "}"
        "}"
        "@media only screen and (min-width: 992px){"
        "input:not([type]), input[type=text]:not(.browser-default), input[type=password]:not(.browser-default), input[type=email]:not(.browser-default), input[type=url]:not(.browser-default), input[type=time]:not(.browser-default), input[type=date]:not(.browser-default), input[type=datetime]:not(.browser-default), input[type=datetime-local]:not(.browser-default), input[type=tel]:not(.browser-default), input[type=number]:not(.browser-default), input[type=search]:not(.browser-default), textarea.materialize-textarea{"
        "font-size: 0.92vw !important;"
        "}"
        "body{"
        "font-size:1.4vw;"
        "}"
        "#search{"
        "text-indent: 3em;"
        "height: 2.6vw !important;"
        "}"
        "}"
        "@media only screen and (min-width: 1200px){"
        "nav, nav .nav-wrapper i, nav a.button-collapse, nav a.button-collapse i{"
        "line-height: 4.4vw;"
        "}"
        ".row .col{"
        "padding: 0 0.75vw;"
        "}"
        "body{"
        "font-size:1.3vw;"
        "}"
        "h6{"
        "margin: 0.6vw 0 0 0;"
        "}"
        "#logo{"
        "width: 4.9vw;"
        "height: 4.1vw;"
        "}"
        "#nameBusiness{"
        "width: 12.2vw;"
        "left: 3.4vw;"
        "}"
        "#nameBusiness > h6 {"
        "font-size: 1.37vw;"
        "}"
        "#nameBusiness > h6 > span:nth-child(3){"
        "font-size: 0.8vw;"
        "}"
        "}"
        "@media only screen and (min-width: 1392px){"
        "nav i, nav [class^='mdi-'], nav [class*='mdi-'], nav i.material-icons{"
        "line-height: 3.5vw !important;"
        "}"
        "body{"
        "font-size:1.3vw;"
        "}"
        "}"
        "@media only screen and (min-width: 1400px){"
        "body{"
        "font-size:1.1vw;"
        "}"
        ":placeholder-shown,::placeholder, ::-webkit-input-placeholder{"
        "font-size: 1em;"
        "}"
        "}"
        #::-moz-placeholder, :ms-input-placeholder, :-moz-placeholder
        #-----IMPORTANT End Block------
        "</style>")

def dropdown_header(name):
    return (f"<a class='dropdown-button col s12 white-text' href='#' data-activates='{name}'>Articulos</a>"
        f"<ul id='{name}' class='dropdown-content'>"
        "<li><a href='#!'>Producto de cabello</a></li>"
        "<li><a href='#!'>Labiales</a></li>"
        #"<li class='divider'></li>"
        "<li><a href='#!'>Base y polvo</a></li>"
        "<li><a href='#!'>Accessorios</a></li>"
        "<li><a href='#!'>Aparatos</a></li>"
        "<li><a href='#!'>Otros</a></li>"
        #"<li><a href='#!'><i class='material-icons'>view_module</i>four</a></li>"
        #"<li><a href='#!'><i class='material-icons'>cloud</i>five</a></li>"
        "</ul>")

def body():
    return ("<header class='black row' style='height: 4.5vw;' >"
    #
        "<nav class='col s4'>"
        "<div class='nav-wrapper col s12'>"
        "<a href='#' data-activates='leftside_header' class='button-collapse'><i class='material-icons ico-menu' >menu</i></a>"
        "<ul class='right hide-on-med-and-down col s12' >"
        "<li class='col s1 offset-s3' ><a href='#'>Inicio</a></li>" +
        f"<li class='col s1 offset-s3' >{dropdown_header('h_article1')}</li>" +
        "<li class='col s1 offset-s3' ><a href='#'>Contacto</a></li>"
        "</ul>"
        "<ul class='side-nav col center-align black' id='leftside_header'>"
        "<li class='col s12' ><a href='#' class='white-text' ><i class='material-icons' style='color: white; position: absolute; left: 80px;' >home</i>Inicio</a></li>" +
        f"<li class='col s12' ><i class='material-icons' style='color: white; position: absolute; left: 80px; top: 40px;' >card_travel</i>{dropdown_header('h_article2')}</li>" +
        "<li class='col s12' ><a href='#' class='white-text' ><i class='material-icons' style='color: white; position: absolute; left: 80px;' >contacts</i>Contacto</a></li>"
        "<li><div id='navbar-container-search' class='col'>"
        "<div id='body-search' class=''>"
        "<form class='' id='form2' >"
        "<div id='search-field' class='input-field' >"
        "<input id='search' type='search' required onkeyup='' placeholder='Buscar Producto' >"
        "<label class='label-icon' for='search' id='ico-search' ><i class='material-icons' style='' >search</i></label>"
        #"<i class='material-icons' >close</i>"
        "</div>"
        "</form>"
        "</div>"
        "</div></li>"
        "</ul>"
        "</div>"
        "</nav>"

    #
        "<nav class='col s8' >"
        "<div class='col s3 offset-l2' >"
        "<img id='logo' class='col left-align' src='{{ url_for('static', filename='img/logo.jpeg')}}' >"
        "<div id='nameBusiness' class='col right-align' >"
        "<h6 class='center-align'>K<span>&</span>K <span>Cosméticos </span><span>Friendly shopping</span></h6>"
        "</div>"
        "</div>"
        "<div id='right_side_header' class='right-align' >"
        "<div id='container-search' class='col hide-on-med-and-down'>"
        "<div id='body-search' class=''>"
        "<form class='' id='form1' >"
        "<div id='search-field' class='input-field' >"
        "<input id='search' type='search' required onkeyup='' placeholder='Buscar Producto' >"
        "<label class='label-icon' for='search' id='ico-search' ><i class='material-icons' >search</i></label>"
        #"<i class='material-icons' >close</i>"
        "</div>"
        "</form>"
        "</div>"
        "</div>"
        "<a id='btn-login' class='ico-person' href='#'><i class='material-icons ico-person' style='display: inline; position: relative;  top: 0.4vw; margin-right: 10px;' >person</i>Iniciar Sesión</a>"
        "</div>"
        "</nav>"
        "</header>")